wm.loadLibs([ 
	"wm.packages.zabonline.extend.ZabExtender",
  "wm.packages.zabonline.mod.DummyServiceVariable",
  "wm.packages.zabonline.mod.Utils",
  "wm.packages.zabonline.mod.ZabonlineCtrl",
  "wm.packages.zabonline.mod.MainCtrl",
  "wm.packages.zabonline.mod.NewAddressCtrl",
  "wm.packages.zabonline.mod.NewFactoryCtrl",
  "wm.packages.zabonline.mod.NewUserCtrl",
  "wm.packages.zabonline.mod.NewRoleCtrl",
  "wm.packages.zabonline.mod.NewTenantCtrl",
  "wm.packages.zabonline.mod.SearchPageCtrl",
  "wm.packages.zabonline.mod.NewCatalogItemCtrl"
]);